_BASE_: "../../images/Lite/base_clip_frozen_image_R50.yaml"
MODEL:
  PSEUDO_VIDEO: False
  FREEZE_WHOLE: False
  TEXT:
    ARCH: clip_frozen
DATASETS:
  TRAIN: ("ovis_train",)
  TEST: ("ovis_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (12000, )
  MAX_ITER: 18000
  CHECKPOINT_PERIOD: 2000
INPUT:
  SAMPLING_FRAME_NUM: 2
  SAMPLING_FRAME_RANGE:  10
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  RANDOM_FLIP: "flip_by_clip"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  # MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 720
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 100000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
OUTPUT_DIR: ./GLEE_Lite_ovis 
